// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AmqpMessage.proto

package com.stupidbeauty.lanime;

public interface AmqpMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.lanime.AmqpMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *要执行的函数名字。
   * </pre>
   *
   * <code>.com.stupidbeauty.lanime.AmqpFunctionName functionName = 1;</code>
   */
  int getFunctionNameValue();
  /**
   * <pre>
   *要执行的函数名字。
   * </pre>
   *
   * <code>.com.stupidbeauty.lanime.AmqpFunctionName functionName = 1;</code>
   */
  com.stupidbeauty.lanime.AmqpFunctionName getFunctionName();

  /**
   * <pre>
   *提交文字消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.lanime.CommitTextMessage commitTextMessage = 2;</code>
   */
  boolean hasCommitTextMessage();
  /**
   * <pre>
   *提交文字消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.lanime.CommitTextMessage commitTextMessage = 2;</code>
   */
  com.stupidbeauty.lanime.CommitTextMessage getCommitTextMessage();
  /**
   * <pre>
   *提交文字消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.lanime.CommitTextMessage commitTextMessage = 2;</code>
   */
  com.stupidbeauty.lanime.CommitTextMessageOrBuilder getCommitTextMessageOrBuilder();

  /**
   * <pre>
   *配置文件信息。
   * </pre>
   *
   * <code>.com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage shutDownAt2100ConfigurationMessage = 3;</code>
   */
  boolean hasShutDownAt2100ConfigurationMessage();
  /**
   * <pre>
   *配置文件信息。
   * </pre>
   *
   * <code>.com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage shutDownAt2100ConfigurationMessage = 3;</code>
   */
  com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage getShutDownAt2100ConfigurationMessage();
  /**
   * <pre>
   *配置文件信息。
   * </pre>
   *
   * <code>.com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage shutDownAt2100ConfigurationMessage = 3;</code>
   */
  com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessageOrBuilder getShutDownAt2100ConfigurationMessageOrBuilder();

  /**
   * <pre>
   *消息的时间戳。
   * </pre>
   *
   * <code>int64 timeStamp = 31;</code>
   */
  long getTimeStamp();
}
