// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommitTextMessage.proto

package com.stupidbeauty.lanime;

public interface CommitTextMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.lanime.CommitTextMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *文字内容。
   * </pre>
   *
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <pre>
   *文字内容。
   * </pre>
   *
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <pre>
   *事务编号。
   * </pre>
   *
   * <code>int64 transactionId = 2;</code>
   */
  long getTransactionId();

  /**
   * <pre>
   *是否要响声
   * </pre>
   *
   * <code>bool beep = 3;</code>
   */
  boolean getBeep();
}
