// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommitTextMessage.proto

package com.stupidbeauty.lanime;

public final class CommitTextMessageProtos {
  private CommitTextMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_lanime_CommitTextMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_lanime_CommitTextMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027CommitTextMessage.proto\022\027com.stupidbea" +
      "uty.lanime\"F\n\021CommitTextMessage\022\014\n\004text\030" +
      "\001 \001(\t\022\025\n\rtransactionId\030\002 \001(\003\022\014\n\004beep\030\003 \001" +
      "(\010B4\n\027com.stupidbeauty.lanimeB\027CommitTex" +
      "tMessageProtosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_stupidbeauty_lanime_CommitTextMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_lanime_CommitTextMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_lanime_CommitTextMessage_descriptor,
        new java.lang.String[] { "Text", "TransactionId", "Beep", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
