// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LanImeMessage.proto

package com.stupidbeauty.lanime;

/**
 * Protobuf type {@code com.stupidbeauty.lanime.LanImeMessage}
 */
public  final class LanImeMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.stupidbeauty.lanime.LanImeMessage)
    LanImeMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LanImeMessage.newBuilder() to construct.
  private LanImeMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LanImeMessage() {
    functionName_ = 0;
    timeStamp_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LanImeMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            functionName_ = rawValue;
            break;
          }
          case 18: {
            com.stupidbeauty.lanime.CommitTextMessage.Builder subBuilder = null;
            if (commitTextMessage_ != null) {
              subBuilder = commitTextMessage_.toBuilder();
            }
            commitTextMessage_ = input.readMessage(com.stupidbeauty.lanime.CommitTextMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(commitTextMessage_);
              commitTextMessage_ = subBuilder.buildPartial();
            }

            break;
          }
          case 248: {

            timeStamp_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.stupidbeauty.lanime.AmqpMessageProtos.internal_static_com_stupidbeauty_lanime_LanImeMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.stupidbeauty.lanime.AmqpMessageProtos.internal_static_com_stupidbeauty_lanime_LanImeMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.stupidbeauty.lanime.LanImeMessage.class, com.stupidbeauty.lanime.LanImeMessage.Builder.class);
  }

  public static final int FUNCTIONNAME_FIELD_NUMBER = 1;
  private int functionName_;
  /**
   * <pre>
   *要执行的函数名字。
   * </pre>
   *
   * <code>.com.stupidbeauty.lanime.LanImeFunctionName functionName = 1;</code>
   */
  public int getFunctionNameValue() {
    return functionName_;
  }
  /**
   * <pre>
   *要执行的函数名字。
   * </pre>
   *
   * <code>.com.stupidbeauty.lanime.LanImeFunctionName functionName = 1;</code>
   */
  public com.stupidbeauty.lanime.LanImeFunctionName getFunctionName() {
    @SuppressWarnings("deprecation")
    com.stupidbeauty.lanime.LanImeFunctionName result = com.stupidbeauty.lanime.LanImeFunctionName.valueOf(functionName_);
    return result == null ? com.stupidbeauty.lanime.LanImeFunctionName.UNRECOGNIZED : result;
  }

  public static final int COMMITTEXTMESSAGE_FIELD_NUMBER = 2;
  private com.stupidbeauty.lanime.CommitTextMessage commitTextMessage_;
  /**
   * <pre>
   *提交文字消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.lanime.CommitTextMessage commitTextMessage = 2;</code>
   */
  public boolean hasCommitTextMessage() {
    return commitTextMessage_ != null;
  }
  /**
   * <pre>
   *提交文字消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.lanime.CommitTextMessage commitTextMessage = 2;</code>
   */
  public com.stupidbeauty.lanime.CommitTextMessage getCommitTextMessage() {
    return commitTextMessage_ == null ? com.stupidbeauty.lanime.CommitTextMessage.getDefaultInstance() : commitTextMessage_;
  }
  /**
   * <pre>
   *提交文字消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.lanime.CommitTextMessage commitTextMessage = 2;</code>
   */
  public com.stupidbeauty.lanime.CommitTextMessageOrBuilder getCommitTextMessageOrBuilder() {
    return getCommitTextMessage();
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 31;
  private long timeStamp_;
  /**
   * <pre>
   *消息的时间戳。
   * </pre>
   *
   * <code>int64 timeStamp = 31;</code>
   */
  public long getTimeStamp() {
    return timeStamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (functionName_ != com.stupidbeauty.lanime.LanImeFunctionName.CommitText.getNumber()) {
      output.writeEnum(1, functionName_);
    }
    if (commitTextMessage_ != null) {
      output.writeMessage(2, getCommitTextMessage());
    }
    if (timeStamp_ != 0L) {
      output.writeInt64(31, timeStamp_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (functionName_ != com.stupidbeauty.lanime.LanImeFunctionName.CommitText.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, functionName_);
    }
    if (commitTextMessage_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCommitTextMessage());
    }
    if (timeStamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(31, timeStamp_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.stupidbeauty.lanime.LanImeMessage)) {
      return super.equals(obj);
    }
    com.stupidbeauty.lanime.LanImeMessage other = (com.stupidbeauty.lanime.LanImeMessage) obj;

    boolean result = true;
    result = result && functionName_ == other.functionName_;
    result = result && (hasCommitTextMessage() == other.hasCommitTextMessage());
    if (hasCommitTextMessage()) {
      result = result && getCommitTextMessage()
          .equals(other.getCommitTextMessage());
    }
    result = result && (getTimeStamp()
        == other.getTimeStamp());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FUNCTIONNAME_FIELD_NUMBER;
    hash = (53 * hash) + functionName_;
    if (hasCommitTextMessage()) {
      hash = (37 * hash) + COMMITTEXTMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getCommitTextMessage().hashCode();
    }
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimeStamp());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.stupidbeauty.lanime.LanImeMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.lanime.LanImeMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.lanime.LanImeMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.lanime.LanImeMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.lanime.LanImeMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.lanime.LanImeMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.lanime.LanImeMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.lanime.LanImeMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stupidbeauty.lanime.LanImeMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.lanime.LanImeMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stupidbeauty.lanime.LanImeMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.lanime.LanImeMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.stupidbeauty.lanime.LanImeMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.stupidbeauty.lanime.LanImeMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.stupidbeauty.lanime.LanImeMessage)
      com.stupidbeauty.lanime.LanImeMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.lanime.AmqpMessageProtos.internal_static_com_stupidbeauty_lanime_LanImeMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.lanime.AmqpMessageProtos.internal_static_com_stupidbeauty_lanime_LanImeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.lanime.LanImeMessage.class, com.stupidbeauty.lanime.LanImeMessage.Builder.class);
    }

    // Construct using com.stupidbeauty.lanime.LanImeMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      functionName_ = 0;

      if (commitTextMessageBuilder_ == null) {
        commitTextMessage_ = null;
      } else {
        commitTextMessage_ = null;
        commitTextMessageBuilder_ = null;
      }
      timeStamp_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.stupidbeauty.lanime.AmqpMessageProtos.internal_static_com_stupidbeauty_lanime_LanImeMessage_descriptor;
    }

    @java.lang.Override
    public com.stupidbeauty.lanime.LanImeMessage getDefaultInstanceForType() {
      return com.stupidbeauty.lanime.LanImeMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.stupidbeauty.lanime.LanImeMessage build() {
      com.stupidbeauty.lanime.LanImeMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.stupidbeauty.lanime.LanImeMessage buildPartial() {
      com.stupidbeauty.lanime.LanImeMessage result = new com.stupidbeauty.lanime.LanImeMessage(this);
      result.functionName_ = functionName_;
      if (commitTextMessageBuilder_ == null) {
        result.commitTextMessage_ = commitTextMessage_;
      } else {
        result.commitTextMessage_ = commitTextMessageBuilder_.build();
      }
      result.timeStamp_ = timeStamp_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.stupidbeauty.lanime.LanImeMessage) {
        return mergeFrom((com.stupidbeauty.lanime.LanImeMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.stupidbeauty.lanime.LanImeMessage other) {
      if (other == com.stupidbeauty.lanime.LanImeMessage.getDefaultInstance()) return this;
      if (other.functionName_ != 0) {
        setFunctionNameValue(other.getFunctionNameValue());
      }
      if (other.hasCommitTextMessage()) {
        mergeCommitTextMessage(other.getCommitTextMessage());
      }
      if (other.getTimeStamp() != 0L) {
        setTimeStamp(other.getTimeStamp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.stupidbeauty.lanime.LanImeMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.stupidbeauty.lanime.LanImeMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int functionName_ = 0;
    /**
     * <pre>
     *要执行的函数名字。
     * </pre>
     *
     * <code>.com.stupidbeauty.lanime.LanImeFunctionName functionName = 1;</code>
     */
    public int getFunctionNameValue() {
      return functionName_;
    }
    /**
     * <pre>
     *要执行的函数名字。
     * </pre>
     *
     * <code>.com.stupidbeauty.lanime.LanImeFunctionName functionName = 1;</code>
     */
    public Builder setFunctionNameValue(int value) {
      functionName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *要执行的函数名字。
     * </pre>
     *
     * <code>.com.stupidbeauty.lanime.LanImeFunctionName functionName = 1;</code>
     */
    public com.stupidbeauty.lanime.LanImeFunctionName getFunctionName() {
      @SuppressWarnings("deprecation")
      com.stupidbeauty.lanime.LanImeFunctionName result = com.stupidbeauty.lanime.LanImeFunctionName.valueOf(functionName_);
      return result == null ? com.stupidbeauty.lanime.LanImeFunctionName.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *要执行的函数名字。
     * </pre>
     *
     * <code>.com.stupidbeauty.lanime.LanImeFunctionName functionName = 1;</code>
     */
    public Builder setFunctionName(com.stupidbeauty.lanime.LanImeFunctionName value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      functionName_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *要执行的函数名字。
     * </pre>
     *
     * <code>.com.stupidbeauty.lanime.LanImeFunctionName functionName = 1;</code>
     */
    public Builder clearFunctionName() {
      
      functionName_ = 0;
      onChanged();
      return this;
    }

    private com.stupidbeauty.lanime.CommitTextMessage commitTextMessage_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.stupidbeauty.lanime.CommitTextMessage, com.stupidbeauty.lanime.CommitTextMessage.Builder, com.stupidbeauty.lanime.CommitTextMessageOrBuilder> commitTextMessageBuilder_;
    /**
     * <pre>
     *提交文字消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.lanime.CommitTextMessage commitTextMessage = 2;</code>
     */
    public boolean hasCommitTextMessage() {
      return commitTextMessageBuilder_ != null || commitTextMessage_ != null;
    }
    /**
     * <pre>
     *提交文字消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.lanime.CommitTextMessage commitTextMessage = 2;</code>
     */
    public com.stupidbeauty.lanime.CommitTextMessage getCommitTextMessage() {
      if (commitTextMessageBuilder_ == null) {
        return commitTextMessage_ == null ? com.stupidbeauty.lanime.CommitTextMessage.getDefaultInstance() : commitTextMessage_;
      } else {
        return commitTextMessageBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *提交文字消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.lanime.CommitTextMessage commitTextMessage = 2;</code>
     */
    public Builder setCommitTextMessage(com.stupidbeauty.lanime.CommitTextMessage value) {
      if (commitTextMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        commitTextMessage_ = value;
        onChanged();
      } else {
        commitTextMessageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *提交文字消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.lanime.CommitTextMessage commitTextMessage = 2;</code>
     */
    public Builder setCommitTextMessage(
        com.stupidbeauty.lanime.CommitTextMessage.Builder builderForValue) {
      if (commitTextMessageBuilder_ == null) {
        commitTextMessage_ = builderForValue.build();
        onChanged();
      } else {
        commitTextMessageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *提交文字消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.lanime.CommitTextMessage commitTextMessage = 2;</code>
     */
    public Builder mergeCommitTextMessage(com.stupidbeauty.lanime.CommitTextMessage value) {
      if (commitTextMessageBuilder_ == null) {
        if (commitTextMessage_ != null) {
          commitTextMessage_ =
            com.stupidbeauty.lanime.CommitTextMessage.newBuilder(commitTextMessage_).mergeFrom(value).buildPartial();
        } else {
          commitTextMessage_ = value;
        }
        onChanged();
      } else {
        commitTextMessageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *提交文字消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.lanime.CommitTextMessage commitTextMessage = 2;</code>
     */
    public Builder clearCommitTextMessage() {
      if (commitTextMessageBuilder_ == null) {
        commitTextMessage_ = null;
        onChanged();
      } else {
        commitTextMessage_ = null;
        commitTextMessageBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *提交文字消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.lanime.CommitTextMessage commitTextMessage = 2;</code>
     */
    public com.stupidbeauty.lanime.CommitTextMessage.Builder getCommitTextMessageBuilder() {
      
      onChanged();
      return getCommitTextMessageFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *提交文字消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.lanime.CommitTextMessage commitTextMessage = 2;</code>
     */
    public com.stupidbeauty.lanime.CommitTextMessageOrBuilder getCommitTextMessageOrBuilder() {
      if (commitTextMessageBuilder_ != null) {
        return commitTextMessageBuilder_.getMessageOrBuilder();
      } else {
        return commitTextMessage_ == null ?
            com.stupidbeauty.lanime.CommitTextMessage.getDefaultInstance() : commitTextMessage_;
      }
    }
    /**
     * <pre>
     *提交文字消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.lanime.CommitTextMessage commitTextMessage = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.stupidbeauty.lanime.CommitTextMessage, com.stupidbeauty.lanime.CommitTextMessage.Builder, com.stupidbeauty.lanime.CommitTextMessageOrBuilder> 
        getCommitTextMessageFieldBuilder() {
      if (commitTextMessageBuilder_ == null) {
        commitTextMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.stupidbeauty.lanime.CommitTextMessage, com.stupidbeauty.lanime.CommitTextMessage.Builder, com.stupidbeauty.lanime.CommitTextMessageOrBuilder>(
                getCommitTextMessage(),
                getParentForChildren(),
                isClean());
        commitTextMessage_ = null;
      }
      return commitTextMessageBuilder_;
    }

    private long timeStamp_ ;
    /**
     * <pre>
     *消息的时间戳。
     * </pre>
     *
     * <code>int64 timeStamp = 31;</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }
    /**
     * <pre>
     *消息的时间戳。
     * </pre>
     *
     * <code>int64 timeStamp = 31;</code>
     */
    public Builder setTimeStamp(long value) {
      
      timeStamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息的时间戳。
     * </pre>
     *
     * <code>int64 timeStamp = 31;</code>
     */
    public Builder clearTimeStamp() {
      
      timeStamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.stupidbeauty.lanime.LanImeMessage)
  }

  // @@protoc_insertion_point(class_scope:com.stupidbeauty.lanime.LanImeMessage)
  private static final com.stupidbeauty.lanime.LanImeMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.stupidbeauty.lanime.LanImeMessage();
  }

  public static com.stupidbeauty.lanime.LanImeMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LanImeMessage>
      PARSER = new com.google.protobuf.AbstractParser<LanImeMessage>() {
    @java.lang.Override
    public LanImeMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LanImeMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LanImeMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LanImeMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.stupidbeauty.lanime.LanImeMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

