// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LanImeMessage.proto

package com.stupidbeauty.lanime;

public interface LanImeMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.lanime.LanImeMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *要执行的函数名字。
   * </pre>
   *
   * <code>.com.stupidbeauty.lanime.LanImeFunctionName functionName = 1;</code>
   */
  int getFunctionNameValue();
  /**
   * <pre>
   *要执行的函数名字。
   * </pre>
   *
   * <code>.com.stupidbeauty.lanime.LanImeFunctionName functionName = 1;</code>
   */
  com.stupidbeauty.lanime.LanImeFunctionName getFunctionName();

  /**
   * <pre>
   *提交文字消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.lanime.CommitTextMessage commitTextMessage = 2;</code>
   */
  boolean hasCommitTextMessage();
  /**
   * <pre>
   *提交文字消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.lanime.CommitTextMessage commitTextMessage = 2;</code>
   */
  com.stupidbeauty.lanime.CommitTextMessage getCommitTextMessage();
  /**
   * <pre>
   *提交文字消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.lanime.CommitTextMessage commitTextMessage = 2;</code>
   */
  com.stupidbeauty.lanime.CommitTextMessageOrBuilder getCommitTextMessageOrBuilder();

  /**
   * <pre>
   *消息的时间戳。
   * </pre>
   *
   * <code>int64 timeStamp = 31;</code>
   */
  long getTimeStamp();
}
