// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sda2Message.proto

package com.stupidbeauty.shutdownat2100;

/**
 * Protobuf type {@code com.stupidbeauty.shutdownat2100.AmqpMessage}
 */
public  final class AmqpMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.stupidbeauty.shutdownat2100.AmqpMessage)
    AmqpMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AmqpMessage.newBuilder() to construct.
  private AmqpMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AmqpMessage() {
    functionName_ = 0;
    timeStamp_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AmqpMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            functionName_ = rawValue;
            break;
          }
          case 18: {
            com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage.Builder subBuilder = null;
            if (shutDownAt2100ConfigurationMessage_ != null) {
              subBuilder = shutDownAt2100ConfigurationMessage_.toBuilder();
            }
            shutDownAt2100ConfigurationMessage_ = input.readMessage(com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(shutDownAt2100ConfigurationMessage_);
              shutDownAt2100ConfigurationMessage_ = subBuilder.buildPartial();
            }

            break;
          }
          case 248: {

            timeStamp_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.stupidbeauty.shutdownat2100.AmqpMessageProtos.internal_static_com_stupidbeauty_shutdownat2100_AmqpMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.stupidbeauty.shutdownat2100.AmqpMessageProtos.internal_static_com_stupidbeauty_shutdownat2100_AmqpMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.stupidbeauty.shutdownat2100.AmqpMessage.class, com.stupidbeauty.shutdownat2100.AmqpMessage.Builder.class);
  }

  public static final int FUNCTIONNAME_FIELD_NUMBER = 1;
  private int functionName_;
  /**
   * <pre>
   *要执行的函数名字。
   * </pre>
   *
   * <code>.com.stupidbeauty.shutdownat2100.Sda2FunctionName functionName = 1;</code>
   */
  public int getFunctionNameValue() {
    return functionName_;
  }
  /**
   * <pre>
   *要执行的函数名字。
   * </pre>
   *
   * <code>.com.stupidbeauty.shutdownat2100.Sda2FunctionName functionName = 1;</code>
   */
  public com.stupidbeauty.shutdownat2100.Sda2FunctionName getFunctionName() {
    @SuppressWarnings("deprecation")
    com.stupidbeauty.shutdownat2100.Sda2FunctionName result = com.stupidbeauty.shutdownat2100.Sda2FunctionName.valueOf(functionName_);
    return result == null ? com.stupidbeauty.shutdownat2100.Sda2FunctionName.UNRECOGNIZED : result;
  }

  public static final int SHUTDOWNAT2100CONFIGURATIONMESSAGE_FIELD_NUMBER = 2;
  private com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage shutDownAt2100ConfigurationMessage_;
  /**
   * <pre>
   *配置文件信息。
   * </pre>
   *
   * <code>.com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage shutDownAt2100ConfigurationMessage = 2;</code>
   */
  public boolean hasShutDownAt2100ConfigurationMessage() {
    return shutDownAt2100ConfigurationMessage_ != null;
  }
  /**
   * <pre>
   *配置文件信息。
   * </pre>
   *
   * <code>.com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage shutDownAt2100ConfigurationMessage = 2;</code>
   */
  public com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage getShutDownAt2100ConfigurationMessage() {
    return shutDownAt2100ConfigurationMessage_ == null ? com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage.getDefaultInstance() : shutDownAt2100ConfigurationMessage_;
  }
  /**
   * <pre>
   *配置文件信息。
   * </pre>
   *
   * <code>.com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage shutDownAt2100ConfigurationMessage = 2;</code>
   */
  public com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessageOrBuilder getShutDownAt2100ConfigurationMessageOrBuilder() {
    return getShutDownAt2100ConfigurationMessage();
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 31;
  private long timeStamp_;
  /**
   * <pre>
   *消息的时间戳。
   * </pre>
   *
   * <code>int64 timeStamp = 31;</code>
   */
  public long getTimeStamp() {
    return timeStamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (functionName_ != com.stupidbeauty.shutdownat2100.Sda2FunctionName.RememberMe.getNumber()) {
      output.writeEnum(1, functionName_);
    }
    if (shutDownAt2100ConfigurationMessage_ != null) {
      output.writeMessage(2, getShutDownAt2100ConfigurationMessage());
    }
    if (timeStamp_ != 0L) {
      output.writeInt64(31, timeStamp_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (functionName_ != com.stupidbeauty.shutdownat2100.Sda2FunctionName.RememberMe.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, functionName_);
    }
    if (shutDownAt2100ConfigurationMessage_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getShutDownAt2100ConfigurationMessage());
    }
    if (timeStamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(31, timeStamp_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.stupidbeauty.shutdownat2100.AmqpMessage)) {
      return super.equals(obj);
    }
    com.stupidbeauty.shutdownat2100.AmqpMessage other = (com.stupidbeauty.shutdownat2100.AmqpMessage) obj;

    boolean result = true;
    result = result && functionName_ == other.functionName_;
    result = result && (hasShutDownAt2100ConfigurationMessage() == other.hasShutDownAt2100ConfigurationMessage());
    if (hasShutDownAt2100ConfigurationMessage()) {
      result = result && getShutDownAt2100ConfigurationMessage()
          .equals(other.getShutDownAt2100ConfigurationMessage());
    }
    result = result && (getTimeStamp()
        == other.getTimeStamp());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FUNCTIONNAME_FIELD_NUMBER;
    hash = (53 * hash) + functionName_;
    if (hasShutDownAt2100ConfigurationMessage()) {
      hash = (37 * hash) + SHUTDOWNAT2100CONFIGURATIONMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getShutDownAt2100ConfigurationMessage().hashCode();
    }
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimeStamp());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.stupidbeauty.shutdownat2100.AmqpMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.shutdownat2100.AmqpMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.shutdownat2100.AmqpMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.shutdownat2100.AmqpMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.shutdownat2100.AmqpMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.shutdownat2100.AmqpMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.shutdownat2100.AmqpMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.shutdownat2100.AmqpMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stupidbeauty.shutdownat2100.AmqpMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.shutdownat2100.AmqpMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stupidbeauty.shutdownat2100.AmqpMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.shutdownat2100.AmqpMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.stupidbeauty.shutdownat2100.AmqpMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.stupidbeauty.shutdownat2100.AmqpMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.stupidbeauty.shutdownat2100.AmqpMessage)
      com.stupidbeauty.shutdownat2100.AmqpMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.shutdownat2100.AmqpMessageProtos.internal_static_com_stupidbeauty_shutdownat2100_AmqpMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.shutdownat2100.AmqpMessageProtos.internal_static_com_stupidbeauty_shutdownat2100_AmqpMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.shutdownat2100.AmqpMessage.class, com.stupidbeauty.shutdownat2100.AmqpMessage.Builder.class);
    }

    // Construct using com.stupidbeauty.shutdownat2100.AmqpMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      functionName_ = 0;

      if (shutDownAt2100ConfigurationMessageBuilder_ == null) {
        shutDownAt2100ConfigurationMessage_ = null;
      } else {
        shutDownAt2100ConfigurationMessage_ = null;
        shutDownAt2100ConfigurationMessageBuilder_ = null;
      }
      timeStamp_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.stupidbeauty.shutdownat2100.AmqpMessageProtos.internal_static_com_stupidbeauty_shutdownat2100_AmqpMessage_descriptor;
    }

    @java.lang.Override
    public com.stupidbeauty.shutdownat2100.AmqpMessage getDefaultInstanceForType() {
      return com.stupidbeauty.shutdownat2100.AmqpMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.stupidbeauty.shutdownat2100.AmqpMessage build() {
      com.stupidbeauty.shutdownat2100.AmqpMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.stupidbeauty.shutdownat2100.AmqpMessage buildPartial() {
      com.stupidbeauty.shutdownat2100.AmqpMessage result = new com.stupidbeauty.shutdownat2100.AmqpMessage(this);
      result.functionName_ = functionName_;
      if (shutDownAt2100ConfigurationMessageBuilder_ == null) {
        result.shutDownAt2100ConfigurationMessage_ = shutDownAt2100ConfigurationMessage_;
      } else {
        result.shutDownAt2100ConfigurationMessage_ = shutDownAt2100ConfigurationMessageBuilder_.build();
      }
      result.timeStamp_ = timeStamp_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.stupidbeauty.shutdownat2100.AmqpMessage) {
        return mergeFrom((com.stupidbeauty.shutdownat2100.AmqpMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.stupidbeauty.shutdownat2100.AmqpMessage other) {
      if (other == com.stupidbeauty.shutdownat2100.AmqpMessage.getDefaultInstance()) return this;
      if (other.functionName_ != 0) {
        setFunctionNameValue(other.getFunctionNameValue());
      }
      if (other.hasShutDownAt2100ConfigurationMessage()) {
        mergeShutDownAt2100ConfigurationMessage(other.getShutDownAt2100ConfigurationMessage());
      }
      if (other.getTimeStamp() != 0L) {
        setTimeStamp(other.getTimeStamp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.stupidbeauty.shutdownat2100.AmqpMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.stupidbeauty.shutdownat2100.AmqpMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int functionName_ = 0;
    /**
     * <pre>
     *要执行的函数名字。
     * </pre>
     *
     * <code>.com.stupidbeauty.shutdownat2100.Sda2FunctionName functionName = 1;</code>
     */
    public int getFunctionNameValue() {
      return functionName_;
    }
    /**
     * <pre>
     *要执行的函数名字。
     * </pre>
     *
     * <code>.com.stupidbeauty.shutdownat2100.Sda2FunctionName functionName = 1;</code>
     */
    public Builder setFunctionNameValue(int value) {
      functionName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *要执行的函数名字。
     * </pre>
     *
     * <code>.com.stupidbeauty.shutdownat2100.Sda2FunctionName functionName = 1;</code>
     */
    public com.stupidbeauty.shutdownat2100.Sda2FunctionName getFunctionName() {
      @SuppressWarnings("deprecation")
      com.stupidbeauty.shutdownat2100.Sda2FunctionName result = com.stupidbeauty.shutdownat2100.Sda2FunctionName.valueOf(functionName_);
      return result == null ? com.stupidbeauty.shutdownat2100.Sda2FunctionName.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *要执行的函数名字。
     * </pre>
     *
     * <code>.com.stupidbeauty.shutdownat2100.Sda2FunctionName functionName = 1;</code>
     */
    public Builder setFunctionName(com.stupidbeauty.shutdownat2100.Sda2FunctionName value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      functionName_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *要执行的函数名字。
     * </pre>
     *
     * <code>.com.stupidbeauty.shutdownat2100.Sda2FunctionName functionName = 1;</code>
     */
    public Builder clearFunctionName() {
      
      functionName_ = 0;
      onChanged();
      return this;
    }

    private com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage shutDownAt2100ConfigurationMessage_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage, com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage.Builder, com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessageOrBuilder> shutDownAt2100ConfigurationMessageBuilder_;
    /**
     * <pre>
     *配置文件信息。
     * </pre>
     *
     * <code>.com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage shutDownAt2100ConfigurationMessage = 2;</code>
     */
    public boolean hasShutDownAt2100ConfigurationMessage() {
      return shutDownAt2100ConfigurationMessageBuilder_ != null || shutDownAt2100ConfigurationMessage_ != null;
    }
    /**
     * <pre>
     *配置文件信息。
     * </pre>
     *
     * <code>.com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage shutDownAt2100ConfigurationMessage = 2;</code>
     */
    public com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage getShutDownAt2100ConfigurationMessage() {
      if (shutDownAt2100ConfigurationMessageBuilder_ == null) {
        return shutDownAt2100ConfigurationMessage_ == null ? com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage.getDefaultInstance() : shutDownAt2100ConfigurationMessage_;
      } else {
        return shutDownAt2100ConfigurationMessageBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *配置文件信息。
     * </pre>
     *
     * <code>.com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage shutDownAt2100ConfigurationMessage = 2;</code>
     */
    public Builder setShutDownAt2100ConfigurationMessage(com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage value) {
      if (shutDownAt2100ConfigurationMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        shutDownAt2100ConfigurationMessage_ = value;
        onChanged();
      } else {
        shutDownAt2100ConfigurationMessageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *配置文件信息。
     * </pre>
     *
     * <code>.com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage shutDownAt2100ConfigurationMessage = 2;</code>
     */
    public Builder setShutDownAt2100ConfigurationMessage(
        com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage.Builder builderForValue) {
      if (shutDownAt2100ConfigurationMessageBuilder_ == null) {
        shutDownAt2100ConfigurationMessage_ = builderForValue.build();
        onChanged();
      } else {
        shutDownAt2100ConfigurationMessageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *配置文件信息。
     * </pre>
     *
     * <code>.com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage shutDownAt2100ConfigurationMessage = 2;</code>
     */
    public Builder mergeShutDownAt2100ConfigurationMessage(com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage value) {
      if (shutDownAt2100ConfigurationMessageBuilder_ == null) {
        if (shutDownAt2100ConfigurationMessage_ != null) {
          shutDownAt2100ConfigurationMessage_ =
            com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage.newBuilder(shutDownAt2100ConfigurationMessage_).mergeFrom(value).buildPartial();
        } else {
          shutDownAt2100ConfigurationMessage_ = value;
        }
        onChanged();
      } else {
        shutDownAt2100ConfigurationMessageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *配置文件信息。
     * </pre>
     *
     * <code>.com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage shutDownAt2100ConfigurationMessage = 2;</code>
     */
    public Builder clearShutDownAt2100ConfigurationMessage() {
      if (shutDownAt2100ConfigurationMessageBuilder_ == null) {
        shutDownAt2100ConfigurationMessage_ = null;
        onChanged();
      } else {
        shutDownAt2100ConfigurationMessage_ = null;
        shutDownAt2100ConfigurationMessageBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *配置文件信息。
     * </pre>
     *
     * <code>.com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage shutDownAt2100ConfigurationMessage = 2;</code>
     */
    public com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage.Builder getShutDownAt2100ConfigurationMessageBuilder() {
      
      onChanged();
      return getShutDownAt2100ConfigurationMessageFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *配置文件信息。
     * </pre>
     *
     * <code>.com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage shutDownAt2100ConfigurationMessage = 2;</code>
     */
    public com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessageOrBuilder getShutDownAt2100ConfigurationMessageOrBuilder() {
      if (shutDownAt2100ConfigurationMessageBuilder_ != null) {
        return shutDownAt2100ConfigurationMessageBuilder_.getMessageOrBuilder();
      } else {
        return shutDownAt2100ConfigurationMessage_ == null ?
            com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage.getDefaultInstance() : shutDownAt2100ConfigurationMessage_;
      }
    }
    /**
     * <pre>
     *配置文件信息。
     * </pre>
     *
     * <code>.com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage shutDownAt2100ConfigurationMessage = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage, com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage.Builder, com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessageOrBuilder> 
        getShutDownAt2100ConfigurationMessageFieldBuilder() {
      if (shutDownAt2100ConfigurationMessageBuilder_ == null) {
        shutDownAt2100ConfigurationMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage, com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage.Builder, com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessageOrBuilder>(
                getShutDownAt2100ConfigurationMessage(),
                getParentForChildren(),
                isClean());
        shutDownAt2100ConfigurationMessage_ = null;
      }
      return shutDownAt2100ConfigurationMessageBuilder_;
    }

    private long timeStamp_ ;
    /**
     * <pre>
     *消息的时间戳。
     * </pre>
     *
     * <code>int64 timeStamp = 31;</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }
    /**
     * <pre>
     *消息的时间戳。
     * </pre>
     *
     * <code>int64 timeStamp = 31;</code>
     */
    public Builder setTimeStamp(long value) {
      
      timeStamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息的时间戳。
     * </pre>
     *
     * <code>int64 timeStamp = 31;</code>
     */
    public Builder clearTimeStamp() {
      
      timeStamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.stupidbeauty.shutdownat2100.AmqpMessage)
  }

  // @@protoc_insertion_point(class_scope:com.stupidbeauty.shutdownat2100.AmqpMessage)
  private static final com.stupidbeauty.shutdownat2100.AmqpMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.stupidbeauty.shutdownat2100.AmqpMessage();
  }

  public static com.stupidbeauty.shutdownat2100.AmqpMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AmqpMessage>
      PARSER = new com.google.protobuf.AbstractParser<AmqpMessage>() {
    @java.lang.Override
    public AmqpMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AmqpMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AmqpMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AmqpMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.stupidbeauty.shutdownat2100.AmqpMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

