// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sda2FunctionName.proto

package com.stupidbeauty.shutdownat2100;

public final class AmqpFunctionNameProtos {
  private AmqpFunctionNameProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026Sda2FunctionName.proto\022\037com.stupidbeau" +
      "ty.shutdownat2100*\345\007\n\020Sda2FunctionName\022\016" +
      "\n\nRememberMe\020\000\022\r\n\tCheckTime\020\001\022\037\n\033ShutDow" +
      "nAt2100Configuration\020\002\022$\n ReportVoiceRec" +
      "ognizeProcessError\020\003\022\032\n\026ReportAudioSound" +
      "Source\020\004\022\020\n\014CancelPhenem\020\005\022\034\n\030SetAvatarB" +
      "ackgroundImage\020\006\022%\n!Set3DEngineCameraPos" +
      "itionRotation\020\007\022\024\n\020SetAvatarVisible\020\010\022\025\n" +
      "\021SetAvatarGeometry\020\t\022\031\n\025ExecutePhenemSeq" +
      "uence\020\n\022\030\n\024ReloadWebApplication\020\013\022\017\n\013Inp" +
      "utAction\020\014\022\023\n\017InputExpression\020\r\022\023\n\017Termi" +
      "nateAction\020\016\022\033\n\027SetAvatarCameraPosition\020" +
      "\017\022\032\n\026ExecuteAvatarEffection\020\020\022\025\n\021HideCam" +
      "eraPreview\020\021\022\026\n\022ExecuteAvatarMacro\020\022\022\025\n\021" +
      "ShowCameraPreview\020\023\022\023\n\017StartFaceDetect\020\024" +
      "\022\026\n\022StartFaceRecognize\020\025\022\022\n\016StartFrameVo" +
      "ip\020\026\022\023\n\017StartQrCodeScan\020\027\022\033\n\027StartExtQrO" +
      "crHybridScan\020\030\022\032\n\026StopExtQrOcrHybridScan" +
      "\020\031\022\022\n\016StopQrCodeScan\020\032\022\010\n\004Quit\020\035\022\031\n\025Repo" +
      "rtVoiceRecognized\020\037\022\037\n\033ReportQrOcrHybrid" +
      "ScanResult\020 \022\032\n\026ReportQrCodeScanResult\020!" +
      "\022\035\n\031ReportFaceRecognizeResult\020\"\022\022\n\016Repor" +
      "tFaceGone\020#\022\026\n\022ReportFaceDetected\020$\022\032\n\026R" +
      "eportFaceDetectUpdate\020%\022\030\n\024ReportSpeechF" +
      "inished\020&\022\027\n\023ReportSpeechStarted\020\'\022\037\n\033Re" +
      "portHumanBodyDetectStatus\020(\022\034\n\030GetHumanB" +
      "odyDetectStatus\020)B;\n\037com.stupidbeauty.sh" +
      "utdownat2100B\026AmqpFunctionNameProtosP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
