// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ShutDownAt2100ConfigurationMessage.proto

package com.stupidbeauty.shutdownat2100;

import com.upokecenter.cbor.CBORObject;
import org.apache.commons.io.FileUtils;
import org.apache.commons.io.filefilter.IOFileFilter;
import org.apache.commons.io.filefilter.TrueFileFilter;
import java.io.ByteArrayOutputStream;

/**
 * Protobuf type {@code com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage}
 */
public  final class ShutDownAt2100ConfigurationMessage 
{
  private static final long serialVersionUID = 0L;

  /**
  *  设置小时数。
  */
  public void setHour(int clock_time)
  {
    hour_=clock_time;
  } // public void setHour(int clock_time)

  /**
  *  设置分钟数。
  */
  public void setMinute(int ClkMnt)
  {
    miniute_=ClkMnt;
  } // public void setMiniute(int ClkMnt)

  /**
  * Parse from object.
  */
  public static ShutDownAt2100ConfigurationMessage parseFrom(CBORObject videoStreamMessage)
  {
    CBORObject hourObject = videoStreamMessage.get("hour");
    int voiceCommand = 21;
    
    if (hourObject!=null) // The hour object exists
    {
      voiceCommand = hourObject.AsInt32();
    } // if (hourObject!=null) // The hour object exists
    
    
    CBORObject minuteObject = videoStreamMessage.get("minute");
    
    
    int packageUrl = 0;
    
    if (minuteObject!=null) // The minute object exists
    {
      packageUrl = minuteObject.AsInt32();
    } // if (minuteObject!=null) // The minute object exists
    
    ShutDownAt2100ConfigurationMessage result = new ShutDownAt2100ConfigurationMessage(); // Result;
    
    result.setHour(voiceCommand);
    result.setMinute(packageUrl);
    
    return result;
  } // public ShutDownAt2100ConfigurationMessage parseFrom(CBORObject versionNameObject)

  public static final int HOUR_FIELD_NUMBER = 1;
  private int hour_;
  /**
   * <pre>
   *小时数。
   * </pre>
   *
   * <code>int32 hour = 1;</code>
   */
  public int getHour() {
    return hour_;
  }

  public static final int MINIUTE_FIELD_NUMBER = 2;
  private int miniute_;
  /**
   * <pre>
   *分钟数。
   * </pre>
   *
   * <code>int32 miniute = 2;</code>
   */
  public int getMinute() 
  {
    return miniute_;
  }

  private byte memoizedIsInitialized = -1;

  // @@protoc_insertion_point(class_scope:com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage)
  private static final com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage();
  }

  public static com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }
}

