// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ShutDownAt2100ConfigurationMessage.proto

package com.stupidbeauty.shutdownat2100;

public interface ShutDownAt2100ConfigurationMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.shutdownat2100.ShutDownAt2100ConfigurationMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *小时数。
   * </pre>
   *
   * <code>int32 hour = 1;</code>
   */
  int getHour();

  /**
   * <pre>
   *分钟数。
   * </pre>
   *
   * <code>int32 miniute = 2;</code>
   */
  int getMiniute();
}
