// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ShutDownAt2100ConfigurationMessage.proto

package com.stupidbeauty.shutdownat2100;

public final class ShutDownAt2100ConfigurationMessageProtos {
  private ShutDownAt2100ConfigurationMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_shutdownat2100_ShutDownAt2100ConfigurationMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_shutdownat2100_ShutDownAt2100ConfigurationMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(ShutDownAt2100ConfigurationMessage.pro" +
      "to\022\037com.stupidbeauty.shutdownat2100\"C\n\"S" +
      "hutDownAt2100ConfigurationMessage\022\014\n\004hou" +
      "r\030\001 \001(\005\022\017\n\007miniute\030\002 \001(\005BM\n\037com.stupidbe" +
      "auty.shutdownat2100B(ShutDownAt2100Confi" +
      "gurationMessageProtosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_stupidbeauty_shutdownat2100_ShutDownAt2100ConfigurationMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_shutdownat2100_ShutDownAt2100ConfigurationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_shutdownat2100_ShutDownAt2100ConfigurationMessage_descriptor,
        new java.lang.String[] { "Hour", "Miniute", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
